CREATE TABLE books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    author      VARCHAR(255),
    isbn        VARCHAR(255),
    price       DECIMAL,
    description VARCHAR(255),
    cover_image VARCHAR(255),
    is_deleted  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);